// app/src/app/footer/footer.component.ts
import { Component } from '@angular/core';
import { VERSION } from '../version';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss',
})
export class FooterComponent {
  version = VERSION;
  year = new Date().getFullYear();
}

<footer class="footer footer-center bg-base-300 text-base-content p-4">
  <aside>
    <p>
      Copyright © {{ year }} - All right reserved by MOVEPLAYGROUND - version
      {{ version }}
    </p>
  </aside>
</footer>

// nextjs-app/components/Footer.tsx
import packageJSON from "../package.json";

export default function Footer() {
  const version = packageJSON.version;
  const year = new Date().getFullYear();

  return (
    <footer className="footer footer-center bg-base-300 text-base-content p-4">
      <aside>
        <p>
          Copyright © {year} - All right reserved by MOVEPLAYGROUND - version{" "}
          {version}
        </p>
      </aside>
    </footer>
  );
}
